newApp/urls.py
from django.contrib import admin
from django.urls import path, include 

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("DisasterID.urls")),
    path('user',include("userProfile.urls"))
]

userProfile/urls.py
from django.urls import path
from userProfile.views import userProfile, add_family_member, edit_family_member, add_shelter_details_view, Ressolv


urlpatterns=[
    path("/profile/<int:email_verification_id>/", userProfile, name='profile-page'),
    path("/add-members/<int:user_profile_id>/", add_family_member, name="add-members"),
    path("/edit-members-details/<int:member_id>/", edit_family_member, name="edit-members-details"),
    path("/add-shelterdetails/<int:user_profile_id>/", add_shelter_details_view, name="add-shelterdetails"),
    path("/ressolv", Ressolv, name="ressolv"),


]

userProfile/models.py
from django.db import models
from django.core.validators import MinValueValidator,MaxValueValidator
from DisasterID.models import UserProfile
# Create your models here.


class FamilyMember(models.Model):
    GENDER_CHOICES = (
        ('Male', 'Male'),
        ('Female', 'Female'),
        ('Other', 'Other'),
    )
    OCCUPATION_CHOICES = (
        ('Student', 'Student'),
        ('Employed', 'Employed'),
        ('Unemployed', 'Unemployed'),
    )
    STATUS_CHOICES = (
        ('Single', 'Single'),
        ('Married', 'Married'),
        ('Divorced', 'Divorced'),
        ('Widowed', 'Widowed'),
    )
    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    gender = models.CharField(max_length=50, choices=GENDER_CHOICES)
    occupation = models.CharField(max_length=50, choices=OCCUPATION_CHOICES)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES)






class Shelter_Details(models.Model):
    # Choices for house type
    HOUSE_TYPE_CHOICES = [
        ('Apartment', 'Apartment'),
        ('House', 'House'),
        ('Bungalow', 'Bungalow'),
        ('Cottage', 'Cottage'),
        ('Other', 'Other'),
    ]
    
    # Choices for extent of house damage
    HOUSE_DAMAGE_CHOICES = [
        ('Self Owned', 'Self Owned'),
        ('Govt. Owned', 'Govt. Owned'),
        ('Rented', 'Rented'),
    ]

    # Choices for availability of toilets
    TOILET_CHOICES = [
        (True, 'Yes'),
        (False, 'No'),
    ]

    # Choices for drinking water source
    DRINKING_WATER_CHOICES = [
        (True, 'Available'),
        (False, 'Not available'),
    ]

    user_profile = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    house_type = models.CharField(max_length=100, choices=HOUSE_TYPE_CHOICES)
    room_numbers = models.IntegerField()
    availability_of_toilets = models.BooleanField(choices=TOILET_CHOICES)
    drinking_water_source = models.BooleanField(choices=DRINKING_WATER_CHOICES)
    ownership_type = models.CharField(max_length=50, choices=HOUSE_DAMAGE_CHOICES)

userProfile/forms.py
from django import forms
from .models import FamilyMember,Shelter_Details

class FamilyMemberForm(forms.ModelForm):
    class Meta:
        model = FamilyMember
        fields = ['user_profile', 'name', 'age', 'gender', 'occupation', 'status']
        widgets = {
            'gender': forms.Select(choices=FamilyMember.GENDER_CHOICES),
            'occupation': forms.Select(choices=FamilyMember.OCCUPATION_CHOICES),
            'status': forms.Select(choices=FamilyMember.STATUS_CHOICES),
        }



class ShelterDetailsForm(forms.ModelForm):
    class Meta:
        model = Shelter_Details
        fields = ['user_profile','house_type', 'room_numbers', 'availability_of_toilets', 'drinking_water_source', 'ownership_type']
        labels = {
            'house_type': 'House Type',
            'room_numbers': 'Room Numbers',
            'availability_of_toilets': 'Availability of Toilets',
            'drinking_water_source': 'Drinking Water Source',
            'ownership_type': 'Ownership Types',
        }
        widgets = {
            'house_type': forms.Select(choices=Shelter_Details.HOUSE_TYPE_CHOICES),
            'room_numbers': forms.NumberInput(attrs={'min': 0}),
            'availability_of_toilets': forms.Select(choices=Shelter_Details.TOILET_CHOICES),
            'drinking_water_source': forms.Select(choices=Shelter_Details.DRINKING_WATER_CHOICES),
            'ownership_type': forms.Select(choices=Shelter_Details.HOUSE_DAMAGE_CHOICES),
        }

userProfile/views.py
from django.shortcuts import render, redirect, get_object_or_404
from DisasterID.models import UserProfile, EmailVerification, BasicUserDetails, UserAddress
from .forms import FamilyMemberForm, ShelterDetailsForm
from .models import FamilyMember, Shelter_Details


# Create your views here.


def userProfile(requests, email_verification_id):
    email_verification = EmailVerification.objects.get(id=email_verification_id)
    basicdetails=BasicUserDetails.objects.get(user_profile_id=email_verification.user_profile.id)
    familyMembers=FamilyMember.objects.filter(user_profile_id=email_verification.user_profile.id)
    shelterdetails=Shelter_Details.objects.filter(user_profile_id=email_verification.user_profile.id)
    return render(requests, "userProfile/home.html", {
        "user_profile": email_verification.user_profile,
        "basicdetails":basicdetails,
        "familymembers":familyMembers,
        "shelterdetails":shelterdetails
    })


def add_family_member(request, user_profile_id):
    user_profile = UserProfile.objects.get(pk=user_profile_id)  # Replace with your logic to retrieve the user_profile object
    email_verification=EmailVerification.objects.get(user_profile_id=user_profile_id)
    if request.method == 'POST':
        form = FamilyMemberForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile-page',email_verification.id )
    else:
        # Assuming you have retrieved the user_profile object based on the current user or some other criteria
        # Replace with your logic to retrieve the user_profile object

        # Pass the user_profile as initial data to the form
        form = FamilyMemberForm(initial={'user_profile': user_profile})

    return render(request, 'userProfile/addMembers.html', {'form': form})


def edit_family_member(request, member_id):
    family_member = FamilyMember.objects.get(pk=member_id)
    email_verification=EmailVerification.objects.get(user_profile_id=family_member.user_profile.id)

    if request.method == 'POST':
        form = FamilyMemberForm(request.POST, instance=family_member)
        if form.is_valid():
            form.save()
            return redirect('profile-page',email_verification.id )
    else:
        form = FamilyMemberForm(instance=family_member)

    return render(request, 'userProfile/edit_family_member.html', {'form': form})


# def shelter_details_view(request):
#     if request.method == 'POST':
#         form = ShelterDetailsForm(request.POST)
#         if form.is_valid():
#             # Save the form data to the database
#             shelter_details = form.save(commit=False)
#             shelter_details.user_profile = request.user.profile  # Assuming you have user profiles
#             shelter_details.save()
#             # Redirect to a success page or render another template
#     else:
#         form = ShelterDetailsForm()
#     return render(request, 'shelter_details.html', {'form': form})

def add_shelter_details_view(request, user_profile_id):
    user_profile = UserProfile.objects.get(pk=user_profile_id)  # Replace with your logic to retrieve the user_profile object
    email_verification=EmailVerification.objects.get(user_profile_id=user_profile_id)
    if request.method == 'POST':
        form = ShelterDetailsForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('profile-page',email_verification.id )
    else:
        # Assuming you have retrieved the user_profile object based on the current user or some other criteria
        # Replace with your logic to retrieve the user_profile object

        # Pass the user_profile as initial data to the form
        form = ShelterDetailsForm(initial={'user_profile': user_profile})

    return render(request, 'userProfile/addshelterdetails.html', {'form': form})


def Ressolv(request):
    return render(request,"userProfile/map.html")

userProfile/templates/userProfile/addMembers.html
<!-- address_input.html -->

{% extends 'base.html' %}
{% load static %}
{%block style%}

{%endblock%}
{% block content %}

            <div class="container mt-5">
                <h2>Add Family Member</h2>
                <form method="post">
                    {% csrf_token %}
                    <div hidden class="form-group row">
                        <label for="id_user_profile" class="col-md-3 col-form-label">User Profile:</label>
                        <div class="col-md-9">
                            {{ form.user_profile }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_name" class="col-md-3 col-form-label">Name:</label>
                        <div class="col-md-9">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_age" class="col-md-3 col-form-label">Age:</label>
                        <div class="col-md-9">
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_gender" class="col-md-3 col-form-label">Gender:</label>
                        <div class="col-md-9">
                            {{ form.gender }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_occupation" class="col-md-3 col-form-label">Occupation:</label>
                        <div class="col-md-9">
                            {{ form.occupation }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_status" class="col-md-3 col-form-label">Status:</label>
                        <div class="col-md-9">
                            {{ form.status }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-9 offset-md-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        
            <!-- Bootstrap JS and jQuery (optional) -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <!-- Second Container -->
        {% comment %} <div class="col-md-6">
                <div class="card" id="map-container">
                    <div class="card-header" id="location-map-header" style="text-align:center;">Location Map</div>
                    <div class="card-body p-0">
                        <div id="map" style="height: 400px;"></div>
                    </div>
                </div>
        </div> {% endcomment %}
    </div>
</div>

<!-- Include Leaflet CSS and JS -->
{% endblock %}

userProfile/templates/userProfile/addshelterdetails.html
<!-- address_input.html -->

{% extends 'base.html' %}
{% load static %}
{%block style%}

{%endblock%}
{% block content %}

            <div class="container mt-5">
                <h2>Add Shelter Details</h2>
                <form method="post">
                    {% csrf_token %}
                    <div hidden class="form-group row">
                        <label for="id_user_profile" class="col-md-3 col-form-label">User Profile:</label>
                        <div class="col-md-9">
                            {{ form.user_profile }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_name" class="col-md-3 col-form-label">House Type:</label>
                        <div class="col-md-9">
                            {{ form.house_type }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_age" class="col-md-3 col-form-label">Number of rooms:</label>
                        <div class="col-md-9">
                            {{ form.room_numbers }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_gender" class="col-md-3 col-form-label">Toilets available:</label>
                        <div class="col-md-9">
                            {{ form.availability_of_toilets }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_occupation" class="col-md-3 col-form-label">Drinking water available:</label>
                        <div class="col-md-9">
                            {{ form.drinking_water_source }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_status" class="col-md-3 col-form-label">Ownership Type:</label>
                        <div class="col-md-9">
                            {{ form.ownership_type }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-9 offset-md-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        
            <!-- Bootstrap JS and jQuery (optional) -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
        <!-- Second Container -->
        {% comment %} <div class="col-md-6">
                <div class="card" id="map-container">
                    <div class="card-header" id="location-map-header" style="text-align:center;">Location Map</div>
                    <div class="card-body p-0">
                        <div id="map" style="height: 400px;"></div>
                    </div>
                </div>
        </div> {% endcomment %}
    </div>
</div>

<!-- Include Leaflet CSS and JS -->
{% endblock %}

userProfile/templates/userProfile/edit_family_member.html
<!-- address_input.html -->

{% extends 'base.html' %}
{% load static %}
{%block style%}

{%endblock%}
{% block content %}



            <div class="container mt-5">
                <h2>Edit Family Member Details</h2>
                <form method="post">
                    {% csrf_token %}
                    <div hidden class="form-group row">
                        <label for="id_user_profile" class="col-md-3 col-form-label">User Profile:</label>
                        <div class="col-md-9">
                            {{ form.user_profile }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_name" class="col-md-3 col-form-label">Name:</label>
                        <div class="col-md-9">
                            {{ form.name }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_age" class="col-md-3 col-form-label">Age:</label>
                        <div class="col-md-9">
                            {{ form.age }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_gender" class="col-md-3 col-form-label">Gender:</label>
                        <div class="col-md-9">
                            {{ form.gender }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_occupation" class="col-md-3 col-form-label">Occupation:</label>
                        <div class="col-md-9">
                            {{ form.occupation }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <label for="id_status" class="col-md-3 col-form-label">Status:</label>
                        <div class="col-md-9">
                            {{ form.status }}
                        </div>
                    </div>
                    <div class="form-group row">
                        <div class="col-md-9 offset-md-3">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        
            <!-- Bootstrap JS and jQuery (optional) -->
            <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
            <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    </div>
</div>

{% endblock %}

userProfile/templates/userProfile/home.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Profile Page
{% endblock %}
{% block style %}
<style>
    /* Add any custom CSS styles here */
    .btn-transparent:hover {
        background-color: #007bff;
    }

    .btn-transparent:focus {
        background-color: #0056b3;
        box-shadow: 0 0 0 0.2rem rgba(0,123,255,.5);
    }

    .btn-transparent {
        border-radius: 20px;
    }
</style>
{% endblock %}
{% block content %}

<div class="container mt-5">
    <div class="progress">
        {% for _ in '12345' %}
        <div class="progress-bar bg-dark" style="width:20%"></div>
        {% endfor %}
        <div class="progress-bar bg-danger" style="width:20%"></div>
    </div>
</div>

<div class="container mt-5">
    <div class="row">
        <!-- First Container -->
        <div class="col-md-12">
            <div class="card" >
                <div class="card-header bg-dark text-white" id="location-map-header" style="text-align:center;">DisasterID Card</div>
                <div class="card-body p-0">
                    <table class="table">
                        <tr>
                            <td>
                                <svg width="65px" height="65px" viewBox="0 0 24 24" fill="#000000" xmlns="http://www.w3.org/2000/svg">
                                    <g id="SVGRepo_bgCarrier" stroke-width="0"/>
                                    <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"/>
                                    <g id="SVGRepo_iconCarrier">
                                        <circle cx="12" cy="6" r="4" fill="#ff0000"/>
                                        <path d="M20 17.5C20 19.9853 20 22 12 22C4 22 4 19.9853 4 17.5C4 15.0147 7.58172 13 12 13C16.4183 13 20 15.0147 20 17.5Z" fill="#ff0000"/>
                                    </g>
                                </svg>
                            </td>
                            <td>
                                <h6>Disaster ID: {{user_profile.disaster_id}}</h6>
                                <h6>Livelihood:{{basicdetails.livelihood}}</h6>
                            </td>
                            <td>
                                <h6>HOF Name:{{basicdetails.name}}</h6>
                                <h6>Total Value of Loss:</h6>
                            </td>
                            <td>
                                <h6>Age:{{basicdetails.age}}</h6>
                                <h6>Total Value of Assistance Received:</h6>
                            </td>
                            <td>
                                <h6>Gender:{{basicdetails.gender}}</h6>
                                <h6>Gap Remained:</h6>
                            </td>
                        </tr>
                    </table>
                    <table class="table" >
                        <tr>
                            <th class="text-center" colspan="7">Family Member Details</th>
                        </tr>
                        {% for member in familymembers %}
                        <tr>
                            <td class="text-center">Name: {{member.name}}</td>
                            <td class="text-center">Age: {{member.age}}</td>
                            <td class="text-center">Gender: {{member.gender}}</td>
                            <td class="text-center">Occupation: {{member.occupation}}</td>
                            <td class="text-center">Status: {{member.status}}</td>
                            <td class="text-center"><a href="{%url "edit-members-details" member.id %}">Edit</a></td>
                            <td class="text-center"><a href="#">Delete</a></td>
                        </tr>
                        {%endfor%}
                        <tr>
                            <td><a href="{%url "add-members" user_profile.id %}">Add New</a></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container mt-5 fixed">
    <div class="progress">
        <div class="progress-bar bg-dark" style="width:20%">
          <a href="#pre-disaster" class="text-white">Basline Data</a>
        </div>
        <div class="progress-bar bg-dark" style="width:20%">
            <a href="#post-disaster" class="text-white">Post-Disaster</a>

        </div>
        <div class="progress-bar bg-dark" style="width:20%">
            <a href="#loss-estimate" class="text-white">Loss Estimate</a>

        </div>
        <div class="progress-bar bg-dark" style="width:20%">
            <a href="#historical-damage" class="text-white">Historical Damage</a>
        </div>
        <div class="progress-bar bg-dark" style="width:20%">
            <a href="#benefits-card" class="text-white">Benefits Card</a>
        </div>
      </div>
    
</div>
<div id="pre-disaster" class="container mt-5">
    <div class="row">
        <div class="row justify-content-center border-1">
            <h4 class="text-center">Basline Household Data</h4>
        </div>
        <!-- First Container -->
        <div class="col-md-12">
            <div class="card" id="map-container">
                <div class="card-header bg-dark" id="location-map-header" style="text-align:center;">
                    <div class="row justify-content-center">
                        <div class="col-md-12 border-1">
                            <div class="btn-group btn-group-horizontal" role="group" style="width: 100%;">
                                <button type="button" class="btn btn-transparent text-white" >Shelter</button>
                                <button type="button" class="btn btn-transparent text-white" >Agriculture</button>
                                <button type="button" class="btn btn-transparent text-white" >Livestocks</button>
                                <button type="button" class="btn btn-transparent text-white" >Fisheries</button>
                                <button type="button" class="btn btn-transparent text-white" >Other Assets</button>

                            </div>
                        </div>
                    </div>
                </div>
            
                <div class="card-body p-0">
                    <table class="table table-hover" >
                        {% if shelterdetails %}
                        {% for shelter in shelterdetails %}
                        <tr>
                            <td class="text-center">House Type:{{shelter.house_type}}</td>
                            <td class="text-center">Number of rooms:{{shelter.room_numbers}}</td>
                            <td class="text-center">Source of drinking water:{{shelter.availability_of_toilets}}</td>
                            <td class="text-center">Availability of toilets:{{shelter.drinking_water_source}}</td>
                            <td class="text-center">Ownership Type:{{shelter.ownership_type}}</td>
                            <td class="text-center"><a href="#">Edit</a></td>
                            <td class="text-center"><a href="#">Delete</a></td>
                        </tr>
                        {%endfor%}
                        {%else%}
                        <tr>
                            <td><a href="{%url "add-shelterdetails" user_profile.id %}">Add New</a></td>
                        </tr>
                        {%endif%}
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div id="post-disaster" class="container mt-5">
    <div class="row">
        <div class="row justify-content-center border-1">
            <h4 class="text-center">Post-Disaster Damage Data</h4>
        </div>
        <!-- First Container -->
        <div class="col-md-12">
            <div class="card" id="map-container">
                <div class="card-header bg-dark" id="location-map-header" style="text-align:center;">
                    <div class="row justify-content-center">
                        <div class="col-md-12 border-1">
                            <div class="btn-group btn-group-horizontal" role="group" style="width: 100%;">
                                <button type="button" class="btn btn-transparent text-white" >Shelter</button>
                                <button type="button" class="btn btn-transparent text-white" >Agriculture</button>
                                <button type="button" class="btn btn-transparent text-white" >Livestocks</button>
                                <button type="button" class="btn btn-transparent text-white" >Fisheries</button>
                                <button type="button" class="btn btn-transparent text-white" >Other Assets</button>

                            </div>
                        </div>
                    </div>
                </div>
            
                <div class="card-body p-0">
                    <table class="table table-hover" >

                        <tr>
                            <td class="text-center">Damage to house:</td>
                            <td class="text-center">Damage to Drinking water source:</td>
                            <td class="text-center">Damage to the toilets:</td>
                            <td class="text-center">Damage to kitchen:</td>
                            <td class="text-center">Insurance Status:</td>
                            <td class="text-center"><a href="#">Edit</a></td>
                            <td class="text-center"><a href="#">Delete</a></td>
                        </tr>
                        <tr>
                            <td><a href="#">Add New</a></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="loss-estimate" class="container mt-5">
    <div class="row">
        {% comment %} <div class="row justify-content-center border-1">
            <h4 class="text-center">Historical-Loss</h4>
        </div> {% endcomment %}
        <!-- First Container -->
        <div class="col-md-12">
            <div class="card" id="map-container">
                <div class="card-header bg-dark" id="location-map-header" style="text-align:center;">
                    <div class="row justify-content-center">
                        <h4 class="text-center text-white">Loss-Estimate</h4>

                    </div>
                </div>
            
                <div class="card-body p-0">
                    <table class="table table-hover" >

                        <tr>
                            <td class="text-center">To:</td>
                            <td class="text-center">Age:</td>
                            <td class="text-center">Gender:</td>
                            <td class="text-center">Occupation:</td>
                            <td class="text-center">Status:</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


<div id="historical-damage" class="container mt-5">
        <div class="row">
            {% comment %} <div class="row justify-content-center border-1">
                <h4 class="text-center">Historical-Loss</h4>
            </div> {% endcomment %}
            <!-- First Container -->
            <div class="col-md-12">
                <div class="card" id="map-container">
                    <div class="card-header bg-dark" id="location-map-header" style="text-align:center;">
                        <div class="row justify-content-center">
                            <h4 class="text-center text-white">Historical-Loss</h4>

                        </div>
                    </div>
                
                    <div class="card-body p-0">
                        <table class="table table-hover" >
    
                            <tr>
                                <td class="text-center">Name:</td>
                                <td class="text-center">Age:</td>
                                <td class="text-center">Gender:</td>
                                <td class="text-center">Occupation:</td>
                                <td class="text-center">Status:</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
<div id="benefits-card" class="container mt-5 mb-5">
        <div class="row">
            {% comment %} <div class="row justify-content-center border-1">
                <h4 class="text-center">Benefits-Card</h4>
            </div> {% endcomment %}
            <!-- First Container -->
            <div class="col-md-12">
                <div class="card" id="map-container">
                    <div class="card-header bg-dark" id="location-map-header" style="text-align:center;">
                        <div class="row justify-content-center">
                            <h4 class="text-center text-white">Benefits-Card</h4>

                        </div>
                    </div>
                
                    <div class="card-body p-0">
                        <table class="table table-hover" >
    
                            <tr>
                                <td class="text-center">Name:</td>
                                <td class="text-center">Age:</td>
                                <td class="text-center">Gender:</td>
                                <td class="text-center">Occupation:</td>
                                <td class="text-center">Status:</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    


{% endblock %}